CREATE DATABASE IF NOT EXISTS marks;
USE marks;


CREATE TABLE IF NOT EXISTS student (
    usn VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE
    
);




CREATE TABLE IF NOT EXISTS marks (
    usn VARCHAR(50) NOT NULL,
    marksIA1 INT NOT NULL,
    marksIA2 INT NOT NULL,
    marksIA3 INT NOT NULL,
    PRIMARY KEY (usn),
    FOREIGN KEY (usn) REFERENCES student(usn)
);



